<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
	<div class="container">
	<span class="payment">
    <img src="http://45.33.122.66/poppys/pub/media/wysiwyg/payment-icon.png" />
    </span>
    <span class="copy"><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
    <div class="clearfix"></div>
    </div>
</small>
