<?php
/**
 * @var $block \Mirasvit\Giftr\Block\Item\Add
 */
?>

<div class="giftr-list"
     data-role="dropdownDialog"
     data-bind="scope: 'giftr-addto__form'"
     data-mage-init='{"dropdownDialog":{
                "appendTo":".add-to-giftr",
                "triggerTarget":".togiftr",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "defaultDialogClass":"giftr-dropdown",
                "show":{
                    "effect":"fade",
                    "duration": 200
                },
                "hide":{
                    "effect":"fade",
                    "duration": 200
                },
                "buttons":[]}}'>
    <div class="registry-list" data-bind="visible: registries.length > 1">
        <div class="registries" data-bind="foreach: registries">
            <label for="registry_>" class="label" data-bind="attr: { for: 'registry_' + value }">
            <input type="checkbox" id="registry_" name="registries[]" value=""
                   data-bind="checked: $parent.selected, value: value, attr: { id: 'registry_' + value }" />
                <span data-bind="text: label"></span>
            </label>
        </div>
        <a id="confirm-add-to-registry" href="#" data-bind="click: addProduct"><?= __('Add') ?></a>
    </div>
    <?php if (!$block->isLoggedIn()): ?>
        <p><?= __(
                'Please, <a href="%1">log in</a> before adding products to registry.',
                $block->getLoginUrl()) ?>
        </p>
    <?php elseif ($block->getCountRegistries() == 0): ?>
        <p><?= __(
                'You have no Gift Registries yet. <a href="%1">Create Gift Registry.</a>',
                $block->getNewRegistryUrl()) ?>
        </p>
    <?php endif ?>
</div>