<?php
/**
 * @var $block \Mirasvit\Giftr\Block\Item\Add
 */
?>
<?php
$isValidationNotRequired = $block->isValidationNotRequired();
$isShowRegistryList = $block->isShowRegistryList();
?>
<div class="product-addto-links add-to-giftr" data-block="addtogiftr">
    <?php if ($block->getMode() === Mirasvit\Giftr\Block\Item\Add::MODE_CONFIGURE): ?>
        <a href="<?= $block->getUpdateUrl() ?>" id="addto-giftr" class="link-giftr"
           data-bind="scope: 'giftr-addto__form'"
           onclick="productAddToCartForm.submitLight(this, this.href); return false;">
            <?= $block->getLabel() ?>
        </a>
    <?php else: ?>
        <div class="giftr-link togiftr" data-bind="scope: 'giftr-addto__form'">
            <a href="#" id="addto-giftr" class="action togiftr link-giftr" data-bind="click: defineBehaviour"><span><?= $block->getLabel() ?></span>
            </a>
        </div>

        <?= $block->getChildHtml('giftrDropdown') ?>
    <?php endif ?>
    <input type="hidden" name="product_id" id="product_id" value="<?= $block->getProduct()->getId() ?>" />
</div>
<script type="text/x-magento-init">
    {
        "*": <?= \Zend\Json\Encoder::encode($block->getJsConfiguration()) ?>
    }
</script>
