<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
$om = \Magento\Framework\App\ObjectManager::getInstance();
?>
<div class="block block-search">
    <label class="search-toggle"></label>
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
      <div class="destop-links">
      <ul class="header links">
      <li>
          <a class="link-account" href="<?php echo $this->getBaseUrl().'customer/account/'; ?>">
          <?php  echo __('My account'); ?>        
          </a>
      </li>
<?php
$customerSession = $om->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) { ?>
<li><a class="account" href="<?php echo $this->getBaseUrl().'customer/account/logout/'; ?>"><?php  echo __('logout'); ?></a></li>
<?php   }
else
{ ?> 
<li class="authorization-link log-in">
  <a class="link-account social-login" href="#social-login-popup" data-effect="mfp-newspaper"><?php  echo __('Sign In'); ?></a>
</li> 
<?php }?>
<li><a class="wishlist" href="<?php echo $this->getBaseUrl().'wishlist/'; ?>"><?php  echo __('My wish list'); ?></a></li> 
  </ul>
      </div>
      <div class="overlay"></div>
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
  require(['jquery'], function () {
    jQuery(document).ready(function(){
        jQuery('.search-toggle').click(function(){
          jQuery('.block-search .block-content').toggleClass('open-search');
        });
        jQuery('.overlay').click(function(){
          jQuery('.block-search .block-content').removeClass('open-search');
        });
    });
  });
</script>