<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Acart
 */
?> 
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output');?>
<table style="width: 100%;">
    <?php if ($block->getQuote()): ?>
        <?php foreach ($block->getQuoteItems() as $_item): ?>
            <?php $_product = $block->getProduct($_item) ;?>
            <tr style="border-bottom: 1px solid #ccc;">
            <td style="vertical-align: middle; padding: 10px 0px">
                <?php if ($block->showImage()): ?>
                    <?php $block->initProductImageHelper($_item, 'amasty_acart_quote_items_list');?>
                    <?php $_imageHelper = $block->getProductImageHelper();?>
                    <div style="display: inline-block; padding-right: 20px; vertical-align: middle;">
                        <a style="text-decoration:none !important;" href="<?php echo $block->getProductUrl($_item);?>">
                            <img style="border:1px solid #ccc;" src="<?php echo $_imageHelper->getUrl()?>" alt="<?php echo $block->escapeHtml($_imageHelper->getLabel())?>" width="<?php echo $_imageHelper->getWidth()?>" height="<?php echo $_imageHelper->getHeight()?>"/>
                        </a>
                    </div>
                <?php endif;?>
            </td>
            <td style="vertical-align: top; padding: 10px 0px">    
                <div style="display: block; vertical-align: top;">
                    <div style="font-size: 14px; margin:0px">
                        <a style="text-decoration:none !important; color: #248bd3;" href="<?php echo $block->getProductUrl($_item);?>">
                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </div>
                    <?php if ( $block->showOptionList() && $_options = $block->getProductOptions($_item)):?>
                        <dl>
                            <?php foreach ($_options as $_option) : ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt style="float: left; clear: left; padding-right: 5px;"><?php echo $block->escapeHtml($_option['label']) ?>: </dt>
                                <dd style="float: left;">
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                    <?php else: ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif;?>
                    <div style="clear: left; font-weight: normal; color: #6e6e6e; font-size: 12px;">
                        <?php if ($block->showDescription()) :?>
                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getDescription(), 'description') ?>
                        <?php endif;?>
                    </div>
                    <div>
                        <?php if ($block->showPrice()) :?>
                        <span style="padding-right: 5px; font-weight: normal; font-size: 13px; color: #323232; margin-bottom: 5px; margin-top: 0;"><?php echo __("Price")?>: </span>
                        <span style="font-size: 17px; font-weight: normal; color: #248bd3;">
                            <?php echo $block->getPrice($_item);?>
                        </span>
                        <?php endif;?>
                    </div>
                </div>

            </td>
            </tr>
        <?php endforeach;?>
    <?php endif;?>
</table>
